IF OBJECT_ID('[dbo].[newview]') IS NOT NULL
	DROP VIEW [dbo].[newview];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[newview]
--WITH ENCRYPTION, SCHEMABINDING, VIEW_METADATA
AS
    SELECT * FROM dbo.Contacts
-- WITH CHECK OPTION
GO
