IF OBJECT_ID('[dbo].[contactview]') IS NOT NULL
	DROP VIEW [dbo].[contactview];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[contactview]
--WITH ENCRYPTION, SCHEMABINDING, VIEW_METADATA
AS
    SELECT * FROM dbo.Contacts
-- WITH CHECK OPTION
GO
